name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  all_main_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9 (lowest supported version)
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pytest
        run: pip install pytest

      - name: Install dependencies
        run: pip install -e .

      - name: Run tests
        run: pytest tests/