name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  all_main_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9 (lowest supported version)
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run tests
        run: poetry run pytest tests/